### ISSUE TITLE
All Starbases Function As Shipyards

### ISSUE THREAD

**Issue by CaptainX3** [CaptainX3/NSC2-Development#150]
For some reason, this seems to be giving all starbases the ability to function as ship yards, INCLUDING ones that haven't been upgraded. Not sure whats causing it, as this bug just pops out of nowhere at some point after starting the game.

_Submitted by Steam User_

**Comment by XXDarrienX** [comment]
Confirmed not a bug, I tested with having a stronghold and several bases, need more information. Most likely is another bug
