### ISSUE TITLE
Fleet Cap Increases Not Working

### ISSUE THREAD

**Issue by CaptainX3** [CaptainX3/NSC2-Development#153]
Apologies if it's already been brought up but there appears to be an issue with the mod when you research fleet cap increases. The first +20 fleet cap research and the +10 that says comes with destroyer tech haven;t been added on.

_Submitted by Steam User_

**Comment by XXDarrienX** [comment]
Confirmed not a bug, the bonus is not Fleet Cap its Command Limit which is working.
