### ISSUE TITLE
Marauder Mischeif.

### ISSUE THREAD

**Issue by Romuken** [CaptainX3/NSC2-Development#183]
The last campaign with a few friends went...wrong.  We were 2, then one hot-joined us by taking the largest empire.  THEN the marauders started raiding (no Kahn yet), focusing on the friend that's hosting the server.  

I've been the target of marauders in previous games.  I know what happens.  He told me that, once they cleared a system, he no longer had control of that system.  It was in his border, under his name, but he couldn't tell the station to upgrade or anything that resides in the system.  He couldn't build in the system either.  When the marauders bombed his planet, he had no control over his faction apparently?  Couldn't build anything, had plenty of resources, and we're unsure if it was a mod or a known issue with the current mode of the game (2.2.2).

Only mods we had:  NSC2.5 and 1080p UI.

**Comment by CaptainX3** [comment]
Nothing in NSC2 makes any changes at all to the Marauders. My guess is that either that is an intended behavior or a 2.2 bug.
